### ISSUE TITLE
Do not duplicate entries when scanning QR code several times

### ISSUE THREAD

**Issue by hirmerpl** [IPVS-AS/MBP2Go#9]
Clear the form before scanning

**Comment by ana-silva** [comment]
Upon scanning the QR a second time, the sensors are added again as below. Therefore, before scanning again (for example, when the did not work properly), the already scanned sensors and actuator should be cleared.
 
![16 03 55](https://user-images.githubusercontent.com/17008080/78258551-b164ad80-74fb-11ea-8bec-c203f2398fc9.jpeg)
